<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>api-test-report-20250809-183643.html</title>
    <style>body {
  font-family: Helvetica, Arial, sans-serif;
  font-size: 12px;
  /* do not increase min-width as some may use split screens */
  min-width: 800px;
  color: #999;
}

h1 {
  font-size: 24px;
  color: black;
}

h2 {
  font-size: 16px;
  color: black;
}

p {
  color: black;
}

a {
  color: #999;
}

table {
  border-collapse: collapse;
}

/******************************
 * SUMMARY INFORMATION
 ******************************/
#environment td {
  padding: 5px;
  border: 1px solid #E6E6E6;
}
#environment tr:nth-child(odd) {
  background-color: #f6f6f6;
}

/******************************
 * TEST RESULT COLORS
 ******************************/
span.passed,
.passed .col-result {
  color: green;
}

span.skipped,
span.xfailed,
span.rerun,
.skipped .col-result,
.xfailed .col-result,
.rerun .col-result {
  color: orange;
}

span.error,
span.failed,
span.xpassed,
.error .col-result,
.failed .col-result,
.xpassed .col-result {
  color: red;
}

/******************************
 * RESULTS TABLE
 *
 * 1. Table Layout
 * 2. Extra
 * 3. Sorting items
 *
 ******************************/
/*------------------
 * 1. Table Layout
 *------------------*/
#results-table {
  border: 1px solid #e6e6e6;
  color: #999;
  font-size: 12px;
  width: 100%;
}
#results-table th,
#results-table td {
  padding: 5px;
  border: 1px solid #E6E6E6;
  text-align: left;
}
#results-table th {
  font-weight: bold;
}

/*------------------
 * 2. Extra
 *------------------*/
.log {
  background-color: #e6e6e6;
  border: 1px solid #e6e6e6;
  color: black;
  display: block;
  font-family: "Courier New", Courier, monospace;
  height: 230px;
  overflow-y: scroll;
  padding: 5px;
  white-space: pre-wrap;
}
.log:only-child {
  height: inherit;
}

div.image {
  border: 1px solid #e6e6e6;
  float: right;
  height: 240px;
  margin-left: 5px;
  overflow: hidden;
  width: 320px;
}
div.image img {
  width: 320px;
}

div.video {
  border: 1px solid #e6e6e6;
  float: right;
  height: 240px;
  margin-left: 5px;
  overflow: hidden;
  width: 320px;
}
div.video video {
  overflow: hidden;
  width: 320px;
  height: 240px;
}

.collapsed {
  display: none;
}

.expander::after {
  content: " (show details)";
  color: #BBB;
  font-style: italic;
  cursor: pointer;
}

.collapser::after {
  content: " (hide details)";
  color: #BBB;
  font-style: italic;
  cursor: pointer;
}

/*------------------
 * 3. Sorting items
 *------------------*/
.sortable {
  cursor: pointer;
}

.sort-icon {
  font-size: 0px;
  float: left;
  margin-right: 5px;
  margin-top: 5px;
  /*triangle*/
  width: 0;
  height: 0;
  border-left: 8px solid transparent;
  border-right: 8px solid transparent;
}
.inactive .sort-icon {
  /*finish triangle*/
  border-top: 8px solid #E6E6E6;
}
.asc.active .sort-icon {
  /*finish triangle*/
  border-bottom: 8px solid #999;
}
.desc.active .sort-icon {
  /*finish triangle*/
  border-top: 8px solid #999;
}
</style></head>
  <body onLoad="init()">
    <script>/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */


function toArray(iter) {
    if (iter === null) {
        return null;
    }
    return Array.prototype.slice.call(iter);
}

function find(selector, elem) { // eslint-disable-line no-redeclare
    if (!elem) {
        elem = document;
    }
    return elem.querySelector(selector);
}

function findAll(selector, elem) {
    if (!elem) {
        elem = document;
    }
    return toArray(elem.querySelectorAll(selector));
}

function sortColumn(elem) {
    toggleSortStates(elem);
    const colIndex = toArray(elem.parentNode.childNodes).indexOf(elem);
    let key;
    if (elem.classList.contains('result')) {
        key = keyResult;
    } else if (elem.classList.contains('links')) {
        key = keyLink;
    } else {
        key = keyAlpha;
    }
    sortTable(elem, key(colIndex));
}

function showAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(showExtras);
}

function hideAllExtras() { // eslint-disable-line no-unused-vars
    findAll('.col-result').forEach(hideExtras);
}

function showExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.remove('collapsed');
    expandcollapse.classList.remove('expander');
    expandcollapse.classList.add('collapser');
}

function hideExtras(colresultElem) {
    const extras = colresultElem.parentNode.nextElementSibling;
    const expandcollapse = colresultElem.firstElementChild;
    extras.classList.add('collapsed');
    expandcollapse.classList.remove('collapser');
    expandcollapse.classList.add('expander');
}

function showFilters() {
    let visibleString = getQueryParameter('visible') || 'all';
    visibleString = visibleString.toLowerCase();
    const checkedItems = visibleString.split(',');

    const filterItems = document.getElementsByClassName('filter');
    for (let i = 0; i < filterItems.length; i++) {
        filterItems[i].hidden = false;

        if (visibleString != 'all') {
            filterItems[i].checked = checkedItems.includes(filterItems[i].getAttribute('data-test-result'));
            filterTable(filterItems[i]);
        }
    }
}

function addCollapse() {
    // Add links for show/hide all
    const resulttable = find('table#results-table');
    const showhideall = document.createElement('p');
    showhideall.innerHTML = '<a href="javascript:showAllExtras()">Show all details</a> / ' +
                            '<a href="javascript:hideAllExtras()">Hide all details</a>';
    resulttable.parentElement.insertBefore(showhideall, resulttable);

    // Add show/hide link to each result
    findAll('.col-result').forEach(function(elem) {
        const collapsed = getQueryParameter('collapsed') || 'Passed';
        const extras = elem.parentNode.nextElementSibling;
        const expandcollapse = document.createElement('span');
        if (extras.classList.contains('collapsed')) {
            expandcollapse.classList.add('expander');
        } else if (collapsed.includes(elem.innerHTML)) {
            extras.classList.add('collapsed');
            expandcollapse.classList.add('expander');
        } else {
            expandcollapse.classList.add('collapser');
        }
        elem.appendChild(expandcollapse);

        elem.addEventListener('click', function(event) {
            if (event.currentTarget.parentNode.nextElementSibling.classList.contains('collapsed')) {
                showExtras(event.currentTarget);
            } else {
                hideExtras(event.currentTarget);
            }
        });
    });
}

function getQueryParameter(name) {
    const match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
    return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
}

function init () { // eslint-disable-line no-unused-vars
    resetSortHeaders();

    addCollapse();

    showFilters();

    sortColumn(find('.initial-sort'));

    findAll('.sortable').forEach(function(elem) {
        elem.addEventListener('click',
            function() {
                sortColumn(elem);
            }, false);
    });
}

function sortTable(clicked, keyFunc) {
    const rows = findAll('.results-table-row');
    const reversed = !clicked.classList.contains('asc');
    const sortedRows = sort(rows, keyFunc, reversed);
    /* Whole table is removed here because browsers acts much slower
     * when appending existing elements.
     */
    const thead = document.getElementById('results-table-head');
    document.getElementById('results-table').remove();
    const parent = document.createElement('table');
    parent.id = 'results-table';
    parent.appendChild(thead);
    sortedRows.forEach(function(elem) {
        parent.appendChild(elem);
    });
    document.getElementsByTagName('BODY')[0].appendChild(parent);
}

function sort(items, keyFunc, reversed) {
    const sortArray = items.map(function(item, i) {
        return [keyFunc(item), i];
    });

    sortArray.sort(function(a, b) {
        const keyA = a[0];
        const keyB = b[0];

        if (keyA == keyB) return 0;

        if (reversed) {
            return keyA < keyB ? 1 : -1;
        } else {
            return keyA > keyB ? 1 : -1;
        }
    });

    return sortArray.map(function(item) {
        const index = item[1];
        return items[index];
    });
}

function keyAlpha(colIndex) {
    return function(elem) {
        return elem.childNodes[1].childNodes[colIndex].firstChild.data.toLowerCase();
    };
}

function keyLink(colIndex) {
    return function(elem) {
        const dataCell = elem.childNodes[1].childNodes[colIndex].firstChild;
        return dataCell == null ? '' : dataCell.innerText.toLowerCase();
    };
}

function keyResult(colIndex) {
    return function(elem) {
        const strings = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed',
            'Skipped', 'Passed'];
        return strings.indexOf(elem.childNodes[1].childNodes[colIndex].firstChild.data);
    };
}

function resetSortHeaders() {
    findAll('.sort-icon').forEach(function(elem) {
        elem.parentNode.removeChild(elem);
    });
    findAll('.sortable').forEach(function(elem) {
        const icon = document.createElement('div');
        icon.className = 'sort-icon';
        icon.textContent = 'vvv';
        elem.insertBefore(icon, elem.firstChild);
        elem.classList.remove('desc', 'active');
        elem.classList.add('asc', 'inactive');
    });
}

function toggleSortStates(elem) {
    //if active, toggle between asc and desc
    if (elem.classList.contains('active')) {
        elem.classList.toggle('asc');
        elem.classList.toggle('desc');
    }

    //if inactive, reset all other functions and add ascending active
    if (elem.classList.contains('inactive')) {
        resetSortHeaders();
        elem.classList.remove('inactive');
        elem.classList.add('active');
    }
}

function isAllRowsHidden(value) {
    return value.hidden == false;
}

function filterTable(elem) { // eslint-disable-line no-unused-vars
    const outcomeAtt = 'data-test-result';
    const outcome = elem.getAttribute(outcomeAtt);
    const classOutcome = outcome + ' results-table-row';
    const outcomeRows = document.getElementsByClassName(classOutcome);

    for(let i = 0; i < outcomeRows.length; i++){
        outcomeRows[i].hidden = !elem.checked;
    }

    const rows = findAll('.results-table-row').filter(isAllRowsHidden);
    const allRowsHidden = rows.length == 0 ? true : false;
    const notFoundMessage = document.getElementById('not-found-message');
    notFoundMessage.hidden = !allRowsHidden;
}
</script>
    <h1>api-test-report-20250809-183643.html</h1>
    <p>Report generated on 09-Aug-2025 at 18:40:13 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a> v3.2.0</p>
    <h2>Summary</h2>
    <p>33 tests ran in 208.53 seconds. </p>
    <p class="filter" hidden="true">(Un)check the boxes to filter the results.</p><input checked="true" class="filter" data-test-result="passed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="passed">11 passed</span>, <input checked="true" class="filter" data-test-result="skipped" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="skipped">0 skipped</span>, <input checked="true" class="filter" data-test-result="failed" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="failed">22 failed</span>, <input checked="true" class="filter" data-test-result="error" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="error">0 errors</span>, <input checked="true" class="filter" data-test-result="xfailed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xfailed">0 expected failures</span>, <input checked="true" class="filter" data-test-result="xpassed" disabled="true" hidden="true" name="filter_checkbox" onChange="filterTable(this)" type="checkbox"/><span class="xpassed">0 unexpected passes</span>
    <h2>Results</h2>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable result initial-sort" col="result">Result</th>
          <th class="sortable" col="name">Test</th>
          <th class="sortable" col="duration">Duration</th>
          <th class="sortable links" col="links">Links</th></tr>
        <tr hidden="true" id="not-found-message">
          <th colspan="4">No results found. Try to check the filters</th></tr></thead>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestPersonaEndpoint::test_persona_valid_message</td>
          <td class="col-duration">8.91</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /persona
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/persona (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestPersonaEndpoint::test_persona_missing_user_id</td>
          <td class="col-duration">8.16</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /persona
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/persona (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestPersonaEndpoint::test_persona_missing_message</td>
          <td class="col-duration">8.14</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /persona
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/persona (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestPersonaEndpoint::test_persona_conversations</td>
          <td class="col-duration">8.11</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona/conversations?user_id=api-test-user (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona/conversations?user_id=api-test-user (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /persona/conversations?user_id=api-test-user
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: 
/dev/persona/conversations?user_id=api-test-user (Caused by ResponseError(&#x27;too 
many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestElevatorEndpoint::test_elevator_call_basic</td>
          <td class="col-duration">8.37</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/elevator/call (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/elevator/call (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /elevator/call
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/elevator/call (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestElevatorEndpoint::test_elevator_missing_mission_id</td>
          <td class="col-duration">7.78</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/elevator/call (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/elevator/call (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /elevator/call
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/elevator/call (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestPSIMEndpoint::test_psim_search_basic</td>
          <td class="col-duration">8.46</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/psim/search (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/psim/search (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /psim/search
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/psim/search (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestPSIMEndpoint::test_psim_search_with_custom_query</td>
          <td class="col-duration">7.73</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/psim/search (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/psim/search (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /psim/search
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/psim/search (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestCoordinatorEndpoint::test_coordinator_mission_status</td>
          <td class="col-duration">8.35</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/coordinator/missions/test-mission-123 (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/coordinator/missions/test-mission-123 (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /coordinator/missions/test-mission-123
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: 
/dev/coordinator/missions/test-mission-123 (Caused by ResponseError(&#x27;too many 
500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestCoordinatorEndpoint::test_coordinator_different_mission_id</td>
          <td class="col-duration">8.28</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/coordinator/missions/python-test-1754775497 (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/coordinator/missions/python-test-1754775497 (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /coordinator/missions/python-test-1754775497
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: 
/dev/coordinator/missions/python-test-1754775497 (Caused by ResponseError(&#x27;too 
many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestCORSHeaders::test_cors_headers_present[/health]</td>
          <td class="col-duration">0.20</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"><span class="error">E   AssertionError: No CORS headers found in response for /health</span><br/>    assert False<br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /health
📊 Status: 200 | ⏱️  Time: 198.99ms | 📦 Size: 60 bytes
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestCORSHeaders::test_cors_headers_present[/director]</td>
          <td class="col-duration">2.95</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"><span class="error">E   AssertionError: No CORS headers found in response for /director</span><br/>    assert False<br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /director
📊 Status: 200 | ⏱️  Time: 2946.46ms | 📦 Size: 128 bytes
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestCORSHeaders::test_cors_headers_present[/persona]</td>
          <td class="col-duration">8.07</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /persona
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/persona (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestCORSHeaders::test_cors_headers_present[/elevator/call]</td>
          <td class="col-duration">7.87</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/elevator/call (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/elevator/call (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /elevator/call
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/elevator/call (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestCORSHeaders::test_cors_headers_present[/psim/search]</td>
          <td class="col-duration">7.70</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/psim/search (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/psim/search (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /psim/search
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/psim/search (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_endpoints.py::TestCORSHeaders::test_cors_headers_present[/coordinator/missions/test-123]</td>
          <td class="col-duration">8.23</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/coordinator/missions/test-123 (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/coordinator/missions/test-123 (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /coordinator/missions/test-123
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/coordinator/missions/test-123 
(Caused by ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_performance.py::TestPerformance::test_response_time_under_threshold</td>
          <td class="col-duration">5.74</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"><span class="error">E   AssertionError: /director took 5559.37ms (threshold: 3000ms)</span><br/>    assert 5559.368133544922 &lt; 3000<br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /health
📊 Status: 200 | ⏱️  Time: 181.41ms | 📦 Size: 60 bytes

🚀 GET /director
📊 Status: 200 | ⏱️  Time: 5557.78ms | 📦 Size: 128 bytes
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_performance.py::TestStressScenarios::test_large_payload_persona</td>
          <td class="col-duration">8.13</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /persona
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/persona (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_performance.py::TestStressScenarios::test_special_characters_in_requests</td>
          <td class="col-duration">8.04</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /persona
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/persona (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_performance.py::TestBoundaryConditions::test_empty_payloads</td>
          <td class="col-duration">8.07</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /persona
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/persona (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_performance.py::TestBoundaryConditions::test_null_values_in_payload</td>
          <td class="col-duration">8.07</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/persona (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 POST /persona
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: /dev/persona (Caused by 
ResponseError(&#x27;too many 500 error responses&#x27;))
<br/></div></td></tr></tbody>
      <tbody class="failed results-table-row">
        <tr>
          <td class="col-result">Failed</td>
          <td class="col-name">test_performance.py::TestBoundaryConditions::test_extremely_long_mission_id</td>
          <td class="col-duration">8.55</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log">urllib3.exceptions.ResponseError: too many 500 error responses<br/><br/>The above exception was the direct cause of the following exception:<br/><span class="error">E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/coordinator/missions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/><br/>During handling of the above exception, another exception occurred:<br/><span class="error">E   requests.exceptions.RetryError: HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, port=443): Max retries exceeded with url: /dev/coordinator/missions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (Caused by ResponseError(&#x27;too many 500 error responses&#x27;))</span><br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET 
/coordinator/missions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
❌ Request failed: 
HTTPSConnectionPool(host=&#x27;pj4vlvxrg7.execute-api.us-east-1.amazonaws.com&#x27;, 
port=443): Max retries exceeded with url: 
/dev/coordinator/missions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
(Caused by ResponseError(&#x27;too many 500 error responses&#x27;))
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
📊 Test Session Complete
                              🔍 Request Summary                               
┌────────┬─────────────────────────────────────┬────────┬───────────┬─────────┐
│ Method │ Endpoint                            │ Status │ Time (ms) │ Success │
├────────┼─────────────────────────────────────┼────────┼───────────┼─────────┤
│ GET    │ /health                             │ 200    │ 1297.31   │ ✅      │
│ GET    │ /health                             │ 200    │ 198.58    │ ✅      │
│ GET    │ /director                           │ 200    │ 4052.94   │ ✅      │
│ GET    │ /director?user_request=Test mission │ 200    │ 5581.57   │ ✅      │
│        │ from Python API tests               │        │           │         │
│ GET    │ /director?user_id=api-test-user     │ 200    │ 6585.56   │ ✅      │
│ POST   │ /persona                            │ 0      │ 8906.19   │ ❌      │
│ POST   │ /persona                            │ 0      │ 8160.71   │ ❌      │
│ POST   │ /persona                            │ 0      │ 8136.42   │ ❌      │
│ GET    │ /persona/conversations?user_id=api… │ 0      │ 8113.98   │ ❌      │
│ POST   │ /elevator/call                      │ 0      │ 8372.06   │ ❌      │
│ POST   │ /elevator/call                      │ 0      │ 7777.36   │ ❌      │
│ POST   │ /psim/search                        │ 0      │ 8457.51   │ ❌      │
│ POST   │ /psim/search                        │ 0      │ 7729.44   │ ❌      │
│ GET    │ /coordinator/missions/test-mission… │ 0      │ 8354.43   │ ❌      │
│ GET    │ /coordinator/missions/python-test-… │ 0      │ 8277.31   │ ❌      │
│ GET    │ /health                             │ 200    │ 198.99    │ ✅      │
│ GET    │ /director                           │ 200    │ 2946.46   │ ✅      │
│ POST   │ /persona                            │ 0      │ 8073.0    │ ❌      │
│ POST   │ /elevator/call                      │ 0      │ 7867.39   │ ❌      │
│ POST   │ /psim/search                        │ 0      │ 7696.95   │ ❌      │
│ GET    │ /coordinator/missions/test-123      │ 0      │ 8232.02   │ ❌      │
│ GET    │ /invalid-endpoint                   │ 404    │ 158.03    │ ❌      │
│ DELETE │ /health                             │ 404    │ 155.14    │ ❌      │
│ GET    │ /health                             │ 200    │ 181.41    │ ✅      │
│ GET    │ /director                           │ 200    │ 5557.78   │ ✅      │
│ GET    │ /health                             │ 200    │ 195.22    │ ✅      │
│ GET    │ /health                             │ 200    │ 1835.04   │ ✅      │
│ GET    │ /health                             │ 200    │ 1841.57   │ ✅      │
│ GET    │ /health                             │ 200    │ 1858.53   │ ✅      │
│ GET    │ /health                             │ 200    │ 1890.46   │ ✅      │
│ GET    │ /health                             │ 200    │ 183.63    │ ✅      │
│ GET    │ /health                             │ 200    │ 188.03    │ ✅      │
│ GET    │ /health                             │ 200    │ 190.26    │ ✅      │
│ GET    │ /health                             │ 200    │ 189.51    │ ✅      │
│ GET    │ /health                             │ 200    │ 186.72    │ ✅      │
│ GET    │ /health                             │ 200    │ 180.63    │ ✅      │
│ GET    │ /health                             │ 200    │ 179.98    │ ✅      │
│ GET    │ /health                             │ 200    │ 180.04    │ ✅      │
│ GET    │ /health                             │ 200    │ 177.69    │ ✅      │
│ GET    │ /health                             │ 200    │ 183.17    │ ✅      │
│ GET    │ /health                             │ 200    │ 195.19    │ ✅      │
│ GET    │ /health                             │ 200    │ 190.03    │ ✅      │
│ GET    │ /health                             │ 200    │ 179.09    │ ✅      │
│ GET    │ /health                             │ 200    │ 186.27    │ ✅      │
│ GET    │ /health                             │ 200    │ 175.74    │ ✅      │
│ GET    │ /health                             │ 200    │ 175.0     │ ✅      │
│ GET    │ /health                             │ 200    │ 184.04    │ ✅      │
│ GET    │ /health                             │ 200    │ 175.95    │ ✅      │
│ GET    │ /health                             │ 200    │ 203.33    │ ✅      │
│ GET    │ /health                             │ 200    │ 268.58    │ ✅      │
│ POST   │ /persona                            │ 0      │ 8135.9    │ ❌      │
│ GET    │ /health                             │ 200    │ 182.65    │ ✅      │
│ GET    │ /health                             │ 200    │ 208.26    │ ✅      │
│ GET    │ /health                             │ 200    │ 182.07    │ ✅      │
│ GET    │ /health                             │ 200    │ 192.09    │ ✅      │
│ GET    │ /health                             │ 200    │ 180.92    │ ✅      │
│ GET    │ /health                             │ 200    │ 190.92    │ ✅      │
│ GET    │ /health                             │ 200    │ 185.02    │ ✅      │
│ GET    │ /health                             │ 200    │ 180.53    │ ✅      │
│ GET    │ /health                             │ 200    │ 178.45    │ ✅      │
│ GET    │ /health                             │ 200    │ 181.61    │ ✅      │
│ POST   │ /persona                            │ 0      │ 8042.99   │ ❌      │
│ POST   │ /persona                            │ 0      │ 8069.75   │ ❌      │
│ POST   │ /persona                            │ 0      │ 8070.77   │ ❌      │
│ GET    │ /coordinator/missions/xxxxxxxxxxxx… │ 0      │ 8402.84   │ ❌      │
└────────┴─────────────────────────────────────┴────────┴───────────┴─────────┘
┌──────────────────────────── Performance Metrics ────────────────────────────┐
│ 📈 Avg: 905.84ms | ⚡ Min: 175.00ms | 🐌 Max: 6585.56ms                     │
└─────────────────────────────────────────────────────────────────────────────┘
💾 Results exported to: api-test-results-20250809-184013.json
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_endpoints.py::TestHealthEndpoint::test_health_check_success</td>
          <td class="col-duration">1.31</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> -----------------------------Captured stdout setup------------------------------ <br/>
🧪 Starting BuildingOS API Test Suite
🌐 Base URL: https://pj4vlvxrg7.execute-api.us-east-1.amazonaws.com/dev
🏷️  Environment: dev
<br/> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /health
📊 Status: 200 | ⏱️  Time: 1297.31ms | 📦 Size: 60 bytes
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_endpoints.py::TestHealthEndpoint::test_health_check_performance</td>
          <td class="col-duration">0.20</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /health
📊 Status: 200 | ⏱️  Time: 198.58ms | 📦 Size: 60 bytes
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_endpoints.py::TestDirectorEndpoint::test_director_basic_request</td>
          <td class="col-duration">4.05</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /director
📊 Status: 200 | ⏱️  Time: 4052.94ms | 📦 Size: 128 bytes
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_endpoints.py::TestDirectorEndpoint::test_director_with_user_request</td>
          <td class="col-duration">5.58</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /director?user_request=Test mission from Python API tests
📊 Status: 200 | ⏱️  Time: 5581.57ms | 📦 Size: 128 bytes
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_endpoints.py::TestDirectorEndpoint::test_director_with_user_id</td>
          <td class="col-duration">6.58</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /director?user_id=api-test-user
📊 Status: 200 | ⏱️  Time: 6585.56ms | 📦 Size: 128 bytes
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_endpoints.py::TestErrorHandling::test_invalid_endpoint</td>
          <td class="col-duration">0.16</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /invalid-endpoint
📊 Status: 404 | ⏱️  Time: 158.03ms | 📦 Size: 23 bytes
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_endpoints.py::TestErrorHandling::test_invalid_method</td>
          <td class="col-duration">0.15</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>
🚀 DELETE /health
📊 Status: 404 | ⏱️  Time: 155.14ms | 📦 Size: 23 bytes
<br/> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_endpoints.py::TestErrorHandling::test_malformed_json</td>
          <td class="col-duration">8.07</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ----------------------------Captured stdout teardown---------------------------- <br/>
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_performance.py::TestPerformance::test_concurrent_health_checks</td>
          <td class="col-duration">1.90</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /health

🚀 GET /health

🚀 GET /health

🚀 GET /health

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 195.22ms | 📦 Size: 60 bytes
📊 Status: 200 | ⏱️  Time: 1835.04ms | 📦 Size: 60 bytes
📊 Status: 200 | ⏱️  Time: 1841.57ms | 📦 Size: 60 bytes
📊 Status: 200 | ⏱️  Time: 1858.53ms | 📦 Size: 60 bytes
📊 Status: 200 | ⏱️  Time: 1890.46ms | 📦 Size: 60 bytes
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_performance.py::TestLoadTesting::test_sustained_load_health_endpoint</td>
          <td class="col-duration">13.33</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>
🔥 Running sustained load test...

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 183.63ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 188.03ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 190.26ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 189.51ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 186.72ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 180.63ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 179.98ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 180.04ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 177.69ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 183.17ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 195.19ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 190.03ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 179.09ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 186.27ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 175.74ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 175.00ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 184.04ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 175.95ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 203.33ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 268.58ms | 📦 Size: 60 bytes
  Making 20 requests... 0:00:13
✅ Success rate: 100.0% (20/20)
⏱️  Avg response: 190.59ms
🐌 Max response: 270.52ms
⚡ Min response: 176.68ms
<br/></div></td></tr></tbody>
      <tbody class="passed results-table-row">
        <tr>
          <td class="col-result">Passed</td>
          <td class="col-name">test_performance.py::TestStressScenarios::test_rapid_successive_requests</td>
          <td class="col-duration">1.88</td>
          <td class="col-links"></td></tr>
        <tr>
          <td class="extra" colspan="4">
            <div class="log"> ------------------------------Captured stdout call------------------------------ <br/>
🚀 GET /health
📊 Status: 200 | ⏱️  Time: 182.65ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 208.26ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 182.07ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 192.09ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 180.92ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 190.92ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 185.02ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 180.53ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 178.45ms | 📦 Size: 60 bytes

🚀 GET /health
📊 Status: 200 | ⏱️  Time: 181.61ms | 📦 Size: 60 bytes
🚀 Rapid requests: 10 in 1.88s
✅ Success rate: 100.0%
<br/></div></td></tr></tbody></table></body></html>